-- NOCTURNO V4
-- Uruchom ten plik w Supabase SQL Editor po bazowej wersji Nocturno.
-- Zawiera V2/V3 + rekrutację CV + dziennik zmiany + polityki managera.

-- =========================================================
-- 1. PROFILE / MANAGER
-- =========================================================
alter table public.profiles enable row level security;

drop policy if exists "profiles_manager_update" on public.profiles;
create policy "profiles_manager_update"
on public.profiles for update to authenticated
using (exists (select 1 from public.profiles me where me.id=auth.uid() and me.role='manager' and me.active=true))
with check (exists (select 1 from public.profiles me where me.id=auth.uid() and me.role='manager' and me.active=true));

drop policy if exists "profiles_manager_select" on public.profiles;
create policy "profiles_manager_select"
on public.profiles for select to authenticated
using (id=auth.uid() or exists (select 1 from public.profiles me where me.id=auth.uid() and me.role='manager' and me.active=true));

-- =========================================================
-- 2. GODZINY / AUDYT
-- =========================================================
alter table public.work_sessions enable row level security;

drop policy if exists "work_sessions_manager_update" on public.work_sessions;
create policy "work_sessions_manager_update"
on public.work_sessions for update to authenticated
using (exists (select 1 from public.profiles me where me.id=auth.uid() and me.role='manager' and me.active=true))
with check (exists (select 1 from public.profiles me where me.id=auth.uid() and me.role='manager' and me.active=true));

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  details text,
  created_at timestamptz not null default now()
);

alter table public.audit_log enable row level security;
drop policy if exists "audit_manager_select" on public.audit_log;
create policy "audit_manager_select" on public.audit_log for select to authenticated
using (exists (select 1 from public.profiles me where me.id=auth.uid() and me.role='manager' and me.active=true));
drop policy if exists "audit_manager_insert" on public.audit_log;
create policy "audit_manager_insert" on public.audit_log for insert to authenticated
with check (actor_id=auth.uid() and exists (select 1 from public.profiles me where me.id=auth.uid() and me.role='manager' and me.active=true));

insert into public.work_periods (started_at,status)
select now(),'open'
where not exists (select 1 from public.work_periods where status='open');

-- =========================================================
-- 3. PARAGONY + STORAGE
-- =========================================================
create table if not exists public.receipts (
  id bigint generated by default as identity primary key,
  employee_id uuid not null references public.profiles(id) on delete cascade,
  amount numeric(12,2) not null check (amount > 0),
  image_path text,
  created_at timestamptz not null default now()
);
create index if not exists receipts_employee_created_idx on public.receipts(employee_id, created_at desc);
create index if not exists receipts_created_idx on public.receipts(created_at desc);

alter table public.receipts enable row level security;
drop policy if exists "receipts_employee_insert" on public.receipts;
create policy "receipts_employee_insert"
on public.receipts for insert to authenticated
with check (employee_id=auth.uid() and exists(select 1 from public.profiles me where me.id=auth.uid() and me.active=true));

drop policy if exists "receipts_employee_select" on public.receipts;
create policy "receipts_employee_select" on public.receipts for select to authenticated
using (employee_id=auth.uid());

drop policy if exists "receipts_manager_select" on public.receipts;
create policy "receipts_manager_select" on public.receipts for select to authenticated
using (exists(select 1 from public.profiles me where me.id=auth.uid() and me.role='manager' and me.active=true));

insert into storage.buckets (id,name,public)
values ('receipts','receipts',false)
on conflict (id) do update set public=false;

drop policy if exists "receipts_storage_insert" on storage.objects;
create policy "receipts_storage_insert" on storage.objects for insert to authenticated
with check (bucket_id='receipts' and ((storage.foldername(name))[1]=auth.uid()::text or exists(select 1 from public.profiles me where me.id=auth.uid() and me.role='manager' and me.active=true)));

drop policy if exists "receipts_storage_select" on storage.objects;
create policy "receipts_storage_select" on storage.objects for select to authenticated
using (bucket_id='receipts' and ((storage.foldername(name))[1]=auth.uid()::text or exists(select 1 from public.profiles me where me.id=auth.uid() and me.role='manager' and me.active=true)));

-- =========================================================
-- 4. REKRUTACJA / CV
-- =========================================================
create extension if not exists pgcrypto;

create table if not exists public.job_applications (
  id uuid primary key default gen_random_uuid(),
  first_name text not null,
  last_name text not null,
  discord_name text not null,
  discord_id text not null,
  position text not null,
  qualifications text not null,
  availability text not null,
  preferred_hours text not null,
  photo_path text not null,
  status text not null default 'Nowe' check (status in ('Nowe','W trakcie','Zaproszono','Przyjęto','Odrzucono')),
  manager_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists job_applications_created_idx on public.job_applications(created_at desc);
create index if not exists job_applications_status_idx on public.job_applications(status);

alter table public.job_applications enable row level security;

drop policy if exists "job_applications_public_insert" on public.job_applications;
create policy "job_applications_public_insert"
on public.job_applications for insert
to anon, authenticated
with check (true);

drop policy if exists "job_applications_manager_select" on public.job_applications;
create policy "job_applications_manager_select"
on public.job_applications for select to authenticated
using (exists(select 1 from public.profiles me where me.id=auth.uid() and me.role='manager' and me.active=true));

drop policy if exists "job_applications_manager_update" on public.job_applications;
create policy "job_applications_manager_update"
on public.job_applications for update to authenticated
using (exists(select 1 from public.profiles me where me.id=auth.uid() and me.role='manager' and me.active=true))
with check (exists(select 1 from public.profiles me where me.id=auth.uid() and me.role='manager' and me.active=true));

insert into storage.buckets (id,name,public)
values ('cv-applications','cv-applications',false)
on conflict (id) do update set public=false;

drop policy if exists "cv_storage_public_insert" on storage.objects;
create policy "cv_storage_public_insert"
on storage.objects for insert
to anon, authenticated
with check (bucket_id='cv-applications' and (storage.foldername(name))[1]='applications');

drop policy if exists "cv_storage_manager_select" on storage.objects;
create policy "cv_storage_manager_select"
on storage.objects for select to authenticated
using (bucket_id='cv-applications' and exists(select 1 from public.profiles me where me.id=auth.uid() and me.role='manager' and me.active=true));

-- =========================================================
-- 5. DZIENNIK ZMIANY
-- =========================================================
create table if not exists public.shift_logs (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  note text not null,
  priority text not null default 'Normalny' check(priority in ('Normalny','Ważne','Pilne')),
  created_at timestamptz not null default now()
);
create index if not exists shift_logs_created_idx on public.shift_logs(created_at desc);

alter table public.shift_logs enable row level security;
drop policy if exists "shift_logs_manager_select" on public.shift_logs;
create policy "shift_logs_manager_select" on public.shift_logs for select to authenticated
using (exists(select 1 from public.profiles me where me.id=auth.uid() and me.role='manager' and me.active=true));

drop policy if exists "shift_logs_manager_insert" on public.shift_logs;
create policy "shift_logs_manager_insert" on public.shift_logs for insert to authenticated
with check (author_id=auth.uid() and exists(select 1 from public.profiles me where me.id=auth.uid() and me.role='manager' and me.active=true));

-- =========================================================
-- 6. UPDATED_AT dla CV
-- =========================================================
create or replace function public.set_job_application_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at=now();
  return new;
end; $$;

drop trigger if exists trg_job_application_updated_at on public.job_applications;
create trigger trg_job_application_updated_at
before update on public.job_applications
for each row execute function public.set_job_application_updated_at();
-- NOCTURNO V5 - NAPRAWA LOGOWANIA / RLS
-- V4 miała rekurencyjne polityki RLS na public.profiles.

create or replace function public.is_nocturno_manager()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role='manager' and p.active=true
  );
$$;
revoke all on function public.is_nocturno_manager() from public;
grant execute on function public.is_nocturno_manager() to authenticated;

alter table public.profiles enable row level security;
drop policy if exists "profiles_manager_select" on public.profiles;
drop policy if exists "profiles_manager_update" on public.profiles;
drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "profiles_select_own_or_manager" on public.profiles;
drop policy if exists "profiles_manager_update_safe" on public.profiles;
create policy "profiles_select_own_or_manager" on public.profiles for select to authenticated
using (id=auth.uid() or public.is_nocturno_manager());
create policy "profiles_manager_update_safe" on public.profiles for update to authenticated
using (public.is_nocturno_manager()) with check (public.is_nocturno_manager());

drop policy if exists "work_sessions_manager_update" on public.work_sessions;
drop policy if exists "work_sessions_manager_update_safe" on public.work_sessions;
create policy "work_sessions_manager_update_safe" on public.work_sessions for update to authenticated
using (public.is_nocturno_manager()) with check (public.is_nocturno_manager());

drop policy if exists "audit_manager_select" on public.audit_log;
drop policy if exists "audit_manager_select_safe" on public.audit_log;
create policy "audit_manager_select_safe" on public.audit_log for select to authenticated using (public.is_nocturno_manager());
drop policy if exists "audit_manager_insert" on public.audit_log;
drop policy if exists "audit_manager_insert_safe" on public.audit_log;
create policy "audit_manager_insert_safe" on public.audit_log for insert to authenticated
with check (actor_id=auth.uid() and public.is_nocturno_manager());

drop policy if exists "receipts_manager_select" on public.receipts;
drop policy if exists "receipts_manager_select_safe" on public.receipts;
create policy "receipts_manager_select_safe" on public.receipts for select to authenticated using (public.is_nocturno_manager());

drop policy if exists "receipts_storage_insert" on storage.objects;
drop policy if exists "receipts_storage_insert_safe" on storage.objects;
create policy "receipts_storage_insert_safe" on storage.objects for insert to authenticated
with check (bucket_id='receipts' and ((storage.foldername(name))[1]=auth.uid()::text or public.is_nocturno_manager()));
drop policy if exists "receipts_storage_select" on storage.objects;
drop policy if exists "receipts_storage_select_safe" on storage.objects;
create policy "receipts_storage_select_safe" on storage.objects for select to authenticated
using (bucket_id='receipts' and ((storage.foldername(name))[1]=auth.uid()::text or public.is_nocturno_manager()));

drop policy if exists "job_applications_manager_select" on public.job_applications;
drop policy if exists "job_applications_manager_select_safe" on public.job_applications;
create policy "job_applications_manager_select_safe" on public.job_applications for select to authenticated using (public.is_nocturno_manager());
drop policy if exists "job_applications_manager_update" on public.job_applications;
drop policy if exists "job_applications_manager_update_safe" on public.job_applications;
create policy "job_applications_manager_update_safe" on public.job_applications for update to authenticated
using (public.is_nocturno_manager()) with check (public.is_nocturno_manager());
drop policy if exists "cv_storage_manager_select" on storage.objects;
drop policy if exists "cv_storage_manager_select_safe" on storage.objects;
create policy "cv_storage_manager_select_safe" on storage.objects for select to authenticated
using (bucket_id='cv-applications' and public.is_nocturno_manager());

drop policy if exists "shift_logs_manager_select" on public.shift_logs;
drop policy if exists "shift_logs_manager_select_safe" on public.shift_logs;
create policy "shift_logs_manager_select_safe" on public.shift_logs for select to authenticated using (public.is_nocturno_manager());
drop policy if exists "shift_logs_manager_insert" on public.shift_logs;
drop policy if exists "shift_logs_manager_insert_safe" on public.shift_logs;
create policy "shift_logs_manager_insert_safe" on public.shift_logs for insert to authenticated
with check (author_id=auth.uid() and public.is_nocturno_manager());

-- Napraw / ustaw konto właściciela.
do $$
declare target_id uuid;
begin
  select id into target_id from auth.users where lower(email)=lower('xjoanna.kruk@gmail.com') limit 1;
  if target_id is null then raise exception 'Nie znaleziono xjoanna.kruk@gmail.com w auth.users'; end if;
  insert into public.profiles(id, full_name, position, role, active)
  values(target_id,'Joanna Kruk','Szef','manager',true)
  on conflict(id) do update set
    full_name=coalesce(nullif(public.profiles.full_name,''), excluded.full_name),
    position='Szef', role='manager', active=true;
end $$;

select u.id,u.email,p.full_name,p.position,p.role,p.active
from auth.users u left join public.profiles p on p.id=u.id
where lower(u.email)=lower('xjoanna.kruk@gmail.com');
